// Auto-extracted from StorageBase.seedKarenderiaData() — keeps base.ts under 3 000 lines.
// Each entry matches the aavinUnions shape used to construct Merchant seed records.

export const aavinUnionsData = [
  { 
    id: "1", 
    name: "Chennai", 
    fullName: "Chennai District Cooperative Milk Producers Union Ltd",
    slug: "aavin-chennai", 
    phone: "044-25388216", 
    email: "md@aavincart.com",
    username: "union.che",
    address: "Madhavaram Milk Colony, Puzhal, Chennai - 600051", 
    lat: "13.0827", 
    lng: "80.2707",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk, Ice Cream, Sweets, Flavoured Milk, Khova, Milk Peda",
    milkProcurement: "12.5 lakh litres/day",
    societies: 2456,
    farmers: 85000
  },
  { 
    id: "2", 
    name: "Coimbatore", 
    fullName: "Coimbatore District Cooperative Milk Producers Union Ltd",
    slug: "aavin-coimbatore", 
    phone: "0422-2222345", 
    email: "md.cbe@aavincart.com",
    username: "union.cbe",
    address: "Perur Chettipalayam Road, Perur, Coimbatore - 641010", 
    lat: "11.0168", 
    lng: "76.9558",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk, Ice Cream, Flavoured Milk",
    milkProcurement: "4.2 lakh litres/day",
    societies: 892,
    farmers: 42000
  },
  { 
    id: "3", 
    name: "Salem", 
    fullName: "Salem District Cooperative Milk Producers Union Ltd",
    slug: "aavin-salem", 
    phone: "0427-2314567", 
    email: "md.slm@aavincart.com",
    username: "union.slm",
    address: "Sithanur, Thalavaippatty Post, Omalur Taluk, Salem - 636302", 
    lat: "11.6643", 
    lng: "78.1460",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk, Ice Cream, Sweets",
    milkProcurement: "3.8 lakh litres/day",
    societies: 756,
    farmers: 38000
  },
  { 
    id: "4", 
    name: "Madurai", 
    fullName: "Madurai District Cooperative Milk Producers Union Ltd",
    slug: "aavin-madurai", 
    phone: "0452-2531234", 
    email: "md.mdu@aavincart.com",
    username: "union.mdu",
    address: "K.K. Nagar, Thirunagar, Madurai - 625006", 
    lat: "9.9252", 
    lng: "78.1198",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk, Ice Cream, Sweets, Traditional Payasam",
    milkProcurement: "3.5 lakh litres/day",
    societies: 684,
    farmers: 35000
  },
  { 
    id: "5", 
    name: "Tiruchirappalli", 
    fullName: "Tiruchirappalli District Cooperative Milk Producers Union Ltd",
    slug: "aavin-trichy", 
    phone: "0431-2760123", 
    email: "md.tcy@aavincart.com",
    username: "union.tcy",
    address: "No. 9, Poosari Palayam, Woraiyur, Tiruchirappalli - 620003", 
    lat: "10.7905", 
    lng: "78.7047",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk, Ice Cream, Milk Powder",
    milkProcurement: "2.8 lakh litres/day",
    societies: 548,
    farmers: 28000
  },
  { 
    id: "6", 
    name: "Thanjavur", 
    fullName: "Thanjavur District Cooperative Milk Producers Union Ltd",
    slug: "aavin-thanjavur", 
    phone: "04362-230456", 
    email: "md.tnj@aavincart.com",
    username: "union.tnj",
    address: "Pattukottai Road, Thanjavur - 613001", 
    lat: "10.7870", 
    lng: "79.1378",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk, Ice Cream, Khova",
    milkProcurement: "2.2 lakh litres/day",
    societies: 425,
    farmers: 22000
  },
  { 
    id: "7", 
    name: "Erode", 
    fullName: "Erode District Cooperative Milk Producers Union Ltd",
    slug: "aavin-erode", 
    phone: "0424-2223456", 
    email: "md.erd@aavincart.com",
    username: "union.erd",
    address: "Perundurai Road, Erode - 638001", 
    lat: "11.3410", 
    lng: "77.7172",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk, Ice Cream, Sweets",
    milkProcurement: "3.2 lakh litres/day",
    societies: 632,
    farmers: 32000
  },
  { 
    id: "8", 
    name: "Tirunelveli", 
    fullName: "Tirunelveli District Cooperative Milk Producers Union Ltd",
    slug: "aavin-tirunelveli", 
    phone: "0462-2501234", 
    email: "md.tnv@aavincart.com",
    username: "union.tnv",
    address: "Palayamkottai Road, Tirunelveli - 627002", 
    lat: "8.7139", 
    lng: "77.7567",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk, Ice Cream, Halwa, Banana Chips",
    milkProcurement: "2.4 lakh litres/day",
    societies: 468,
    farmers: 24000
  },
  { 
    id: "9", 
    name: "Vellore", 
    fullName: "Vellore District Cooperative Milk Producers Union Ltd",
    slug: "aavin-vellore", 
    phone: "0416-2241567", 
    email: "md.vlr@aavincart.com",
    username: "union.vlr",
    address: "Sathuvachari, Vellore - 632009", 
    lat: "12.9165", 
    lng: "79.1325",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk, Ice Cream",
    milkProcurement: "2.1 lakh litres/day",
    societies: 412,
    farmers: 21000
  },
  { 
    id: "10", 
    name: "Villupuram", 
    fullName: "Villupuram District Cooperative Milk Producers Union Ltd",
    slug: "aavin-villupuram", 
    phone: "04146-222789", 
    email: "md.vpm@aavincart.com",
    username: "union.vpm",
    address: "Tindivanam Road, Villupuram - 605602", 
    lat: "11.9401", 
    lng: "79.4861",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk",
    milkProcurement: "1.8 lakh litres/day",
    societies: 356,
    farmers: 18000
  },
  { 
    id: "11", 
    name: "Kancheepuram", 
    fullName: "Kancheepuram District Cooperative Milk Producers Union Ltd",
    slug: "aavin-kancheepuram", 
    phone: "044-27252345", 
    email: "md.kpm@aavincart.com",
    username: "union.kpm",
    address: "GST Road, Kancheepuram - 631501", 
    lat: "12.8342", 
    lng: "79.7036",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk, Ice Cream",
    milkProcurement: "2.0 lakh litres/day",
    societies: 392,
    farmers: 20000
  },
  { 
    id: "12", 
    name: "Tiruvannamalai", 
    fullName: "Tiruvannamalai District Cooperative Milk Producers Union Ltd",
    slug: "aavin-tiruvannamalai", 
    phone: "04175-230456", 
    email: "md.tvm@aavincart.com",
    username: "union.tvm",
    address: "Polur Road, Tiruvannamalai - 606601", 
    lat: "12.2253", 
    lng: "79.0747",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk",
    milkProcurement: "1.6 lakh litres/day",
    societies: 312,
    farmers: 16000
  },
  { 
    id: "13", 
    name: "Cuddalore", 
    fullName: "Cuddalore District Cooperative Milk Producers Union Ltd",
    slug: "aavin-cuddalore", 
    phone: "04142-224567", 
    email: "md.cdl@aavincart.com",
    username: "union.cdl",
    address: "Chidambaram Road, Cuddalore - 607001", 
    lat: "11.7480", 
    lng: "79.7714",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk, Ice Cream",
    milkProcurement: "1.4 lakh litres/day",
    societies: 278,
    farmers: 14000
  },
  { 
    id: "14", 
    name: "Nagapattinam", 
    fullName: "Nagapattinam District Cooperative Milk Producers Union Ltd",
    slug: "aavin-nagapattinam", 
    phone: "04365-241234", 
    email: "md.ngp@aavincart.com",
    username: "union.ngp",
    address: "Mayiladuthurai Road, Nagapattinam - 611001", 
    lat: "10.7672", 
    lng: "79.8449",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk",
    milkProcurement: "1.2 lakh litres/day",
    societies: 234,
    farmers: 12000
  },
  { 
    id: "15", 
    name: "Dindigul", 
    fullName: "Dindigul District Cooperative Milk Producers Union Ltd",
    slug: "aavin-dindigul", 
    phone: "0451-2421234", 
    email: "md.ddg@aavincart.com",
    username: "union.ddg",
    address: "Palani Road, Dindigul - 624001", 
    lat: "10.3624", 
    lng: "77.9695",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk, Ice Cream, Sweets",
    milkProcurement: "1.9 lakh litres/day",
    societies: 378,
    farmers: 19000
  },
  { 
    id: "16", 
    name: "Theni", 
    fullName: "Theni District Cooperative Milk Producers Union Ltd",
    slug: "aavin-theni", 
    phone: "04546-252345", 
    email: "md.tni@aavincart.com",
    username: "union.tni",
    address: "Periyakulam Road, Theni - 625531", 
    lat: "10.0104", 
    lng: "77.4768",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk",
    milkProcurement: "1.3 lakh litres/day",
    societies: 256,
    farmers: 13000
  },
  { 
    id: "17", 
    name: "Virudhunagar", 
    fullName: "Virudhunagar District Cooperative Milk Producers Union Ltd",
    slug: "aavin-virudhunagar", 
    phone: "04562-243456", 
    email: "md.vdn@aavincart.com",
    username: "union.vdn",
    address: "Sivakasi Road, Virudhunagar - 626001", 
    lat: "9.5680", 
    lng: "77.9624",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk, Sweets",
    milkProcurement: "1.5 lakh litres/day",
    societies: 298,
    farmers: 15000
  },
  { 
    id: "18", 
    name: "Ramanathapuram", 
    fullName: "Ramanathapuram District Cooperative Milk Producers Union Ltd",
    slug: "aavin-ramanathapuram", 
    phone: "04567-230567", 
    email: "md.rmd@aavincart.com",
    username: "union.rmd",
    address: "Mandapam Road, Ramanathapuram - 623501", 
    lat: "9.3639", 
    lng: "78.8395",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk",
    milkProcurement: "0.9 lakh litres/day",
    societies: 178,
    farmers: 9000
  },
  { 
    id: "19", 
    name: "Sivaganga", 
    fullName: "Sivaganga District Cooperative Milk Producers Union Ltd",
    slug: "aavin-sivaganga", 
    phone: "04575-241234", 
    email: "md.svg@aavincart.com",
    username: "union.svg",
    address: "Karaikudi Road, Sivaganga - 630561", 
    lat: "9.8477", 
    lng: "78.4815",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk, Chettinad Sweets",
    milkProcurement: "1.1 lakh litres/day",
    societies: 218,
    farmers: 11000
  },
  { 
    id: "20", 
    name: "Thoothukudi", 
    fullName: "Thoothukudi District Cooperative Milk Producers Union Ltd",
    slug: "aavin-thoothukudi", 
    phone: "0461-2345678", 
    email: "md.tut@aavincart.com",
    username: "union.tut",
    address: "Palayamkottai Road, Thoothukudi - 628002", 
    lat: "8.7642", 
    lng: "78.1348",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk, Ice Cream",
    milkProcurement: "1.4 lakh litres/day",
    societies: 274,
    farmers: 14000
  },
  { 
    id: "21", 
    name: "Kanyakumari", 
    fullName: "Kanyakumari District Cooperative Milk Producers Union Ltd",
    slug: "aavin-kanyakumari", 
    phone: "04652-230567", 
    email: "md.kyk@aavincart.com",
    username: "union.kyk",
    address: "Nagercoil Road, Kanyakumari - 629001", 
    lat: "8.0883", 
    lng: "77.5385",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk, Banana Products",
    milkProcurement: "1.0 lakh litres/day",
    societies: 198,
    farmers: 10000
  },
  { 
    id: "22", 
    name: "Namakkal", 
    fullName: "Namakkal District Cooperative Milk Producers Union Ltd",
    slug: "aavin-namakkal", 
    phone: "04286-230789", 
    email: "md.nmk@aavincart.com",
    username: "union.nmk",
    address: "Tiruchengode Road, Namakkal - 637001", 
    lat: "11.2189", 
    lng: "78.1674",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk, Eggs, Poultry Products",
    milkProcurement: "2.3 lakh litres/day",
    societies: 456,
    farmers: 23000
  },
  { 
    id: "23", 
    name: "Dharmapuri", 
    fullName: "Dharmapuri District Cooperative Milk Producers Union Ltd",
    slug: "aavin-dharmapuri", 
    phone: "04342-230456", 
    email: "md.dpi@aavincart.com",
    username: "union.dpi",
    address: "Krishnagiri Road, Dharmapuri - 636701", 
    lat: "12.1211", 
    lng: "78.1582",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk",
    milkProcurement: "1.7 lakh litres/day",
    societies: 334,
    farmers: 17000
  },
  { 
    id: "24", 
    name: "Krishnagiri", 
    fullName: "Krishnagiri District Cooperative Milk Producers Union Ltd",
    slug: "aavin-krishnagiri", 
    phone: "04343-230567", 
    email: "md.kgi@aavincart.com",
    username: "union.kgi",
    address: "Hosur Road, Krishnagiri - 635001", 
    lat: "12.5266", 
    lng: "78.2141",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk, Mango Products",
    milkProcurement: "1.8 lakh litres/day",
    societies: 356,
    farmers: 18000
  },
  { 
    id: "25", 
    name: "Tiruppur", 
    fullName: "Tiruppur District Cooperative Milk Producers Union Ltd",
    slug: "aavin-tiruppur", 
    phone: "0421-2230678", 
    email: "md.tpr@aavincart.com",
    username: "union.tpr",
    address: "Avinashi Road, Tiruppur - 641601", 
    lat: "11.1085", 
    lng: "77.3411",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk, Ice Cream",
    milkProcurement: "2.5 lakh litres/day",
    societies: 492,
    farmers: 25000
  },
  { 
    id: "26", 
    name: "Karur", 
    fullName: "Karur District Cooperative Milk Producers Union Ltd",
    slug: "aavin-karur", 
    phone: "04324-230789", 
    email: "md.krr@aavincart.com",
    username: "union.krr",
    address: "Trichy Road, Karur - 639001", 
    lat: "10.9601", 
    lng: "78.0766",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk",
    milkProcurement: "1.2 lakh litres/day",
    societies: 238,
    farmers: 12000
  },
  { 
    id: "27", 
    name: "Ariyalur", 
    fullName: "Ariyalur District Cooperative Milk Producers Union Ltd",
    slug: "aavin-ariyalur", 
    phone: "04329-230456", 
    email: "md.ayr@aavincart.com",
    username: "union.ayr",
    address: "Perambalur Road, Ariyalur - 621704", 
    lat: "11.1386", 
    lng: "79.0786",
    products: "Milk, Curd, Paneer, Butter, Ghee, Buttermilk",
    milkProcurement: "0.8 lakh litres/day",
    societies: 158,
    farmers: 8000
  },
];
