import { readFileSync } from 'fs';
import { 
  type Restaurant, 
  type MenuItem, 
  type Order, 
  type User,
  deliveryPoints as deliveryPointsTable,
  type DeliveryPoint,
  type InsertRestaurant, 
  type InsertMenuItem, 
  type InsertOrder,
  type InsertUser,
  type InsertDeliveryPoint,
  // Karenderia entities
  type Merchant,
  type Client,
  type Item,
  type Plan,
  type Invoice,
  type Payout,
  type Reservation,
  type Promo,
  type Notification,
  type Earning,
  type Attribute,
  type MarketingCampaign,
  type PaymentGateway,
  type UpiTransaction,
  type InsertMerchant,
  type InsertClient,
  type InsertItem,
  type InsertPlan,
  type InsertInvoice,
  type InsertPayout,
  type InsertReservation,
  type InsertPromo,
  type InsertNotification,
  type InsertEarning,
  type InsertAttribute,
  type InsertMarketingCampaign,
  type InsertPaymentGateway,
  type InsertUpiTransaction,
  type RazorpayTransaction,
  type InsertRazorpayTransaction,
  type CashfreeTransaction,
  type InsertCashfreeTransaction,
  cashfreeTransactions,
  type CashfreePaymentLink,
  type InsertCashfreePaymentLink,
  cashfreePaymentLinks,
  type CashfreeSplitVendor,
  type InsertCashfreeSplitVendor,
  cashfreeSplitVendors,
  type CashfreeOrderSplit,
  type InsertCashfreeOrderSplit,
  cashfreeOrderSplits,
  type CashfreeBeneficiary,
  type InsertCashfreeBeneficiary,
  cashfreeBeneficiaries,
  type CashfreePayout,
  type InsertCashfreePayout,
  cashfreePayouts,
  type CashfreeSoftposTerminal,
  type InsertCashfreeSoftposTerminal,
  cashfreeSoftposTerminals,
  type PricingTier,
  type InsertPricingTier,
  // E-way Bill entities
  type EwayBill,
  type InsertEwayBill,
  type EwayBillConfig,
  type InsertEwayBillConfig,
  type EwayBillLog,
  type InsertEwayBillLog,
  type HsnCode,
  // GST Returns
  type GstReturn,
  type InsertGstReturn,
  type InsertHsnCode,
  // Delhivery entities
  type DelhiveryConfig,
  type InsertDelhiveryConfig,
  type DelhiveryWarehouse,
  type InsertDelhiveryWarehouse,
  type DelhiveryShipment,
  type InsertDelhiveryShipment,
  delhiveryConfig,
  delhiveryWarehouses,
  delhiveryShipments,
  // Wholesale Dealers
  type WholesaleDealer,
  wholesaleDealers,
  // Fresh Milk Dealers
  type FreshMilkDealer,
  freshMilkDealers,
  // Media Files
  type MediaFile,
  type InsertMediaFile,
  mediaFiles,
  // Agents
  type Agent,
  type InsertAgent,
  agents,
  // Inventory
  type Inventory,
  type InsertInventory,
  type InventoryTransaction,
  type InsertInventoryTransaction,
  inventory,
  inventoryTransactions,
  // Master Orders
  type MasterOrder,
  type InsertMasterOrder,
  masterOrders,
  // Wallet
  type Wallet,
  type InsertWallet,
  type WalletTransaction,
  type InsertWalletTransaction,
  wallets,
  walletTransactions,
  // Delivery Configuration
  type DeliveryConfiguration,
  type InsertDeliveryConfiguration,
  type DeliveryRoute,
  type InsertDeliveryRoute,
  type DeliveryEarnings,
  type InsertDeliveryEarnings,
  deliveryConfiguration,
  deliveryRoutes,
  deliveryEarnings,
  // B2B Invoices
  type B2BInvoice,
  type InsertB2BInvoice,
  b2bInvoices,
  // API Settings
  type ApiSetting,
  type InsertApiSetting,
  apiSettings,
  // User Hierarchy
  type UserHierarchy,
  type InsertUserHierarchy,
  userHierarchy,
  // B2B Registrations
  type B2bRegistration,
  type InsertB2bRegistration,
  b2bRegistrations,
  type B2bApprovalHistory,
  b2bApprovalHistory,
  // Fresh Milk Dispatch
  type FreshMilkRoute,
  type InsertFreshMilkRoute,
  type FreshMilkDispatch,
  type InsertFreshMilkDispatch,
  type FreshMilkDispatchItem,
  type InsertFreshMilkDispatchItem,
  type FreshMilkReturn,
  type InsertFreshMilkReturn,
  // Database table imports  
  users,
  restaurants,
  menuItems,
  orders,
  merchants,
  clients,
  items,
  plans,
  invoices,
  payouts,
  reservations,
  promos,
  notifications,
  earnings,
  attributes,
  marketingCampaigns,
  paymentGateways,
  upiTransactions,
  pricingTiers,
  ewayBills,
  ewayBillConfig,
  ewayBillLogs,
  hsnCodes,
  gstReturns,
  orders as ordersTable
} from "@shared/schema";
import { randomUUID, scrypt, scryptSync } from "crypto";
import { promisify } from "util";
import { eq, desc, asc, like, or, sql, and, inArray } from "drizzle-orm";
import { db } from "../db";
import { aavinUnionsData } from './aavin-unions-data';


import type { IStorage } from './types';

export abstract class StorageBase {
  protected restaurants: Map<string, Restaurant> = new Map();
  protected menuItems: Map<string, MenuItem> = new Map();
  protected orders: Map<string, Order> = new Map();
  protected deliveryPoints: Map<string, DeliveryPoint> = new Map();
  
  // Karenderia entities
  protected merchants: Map<string, Merchant> = new Map();
  protected clients: Map<string, Client> = new Map();
  protected items: Map<string, Item> = new Map();
  protected plans: Map<string, Plan> = new Map();
  protected invoices: Map<string, Invoice> = new Map();
  protected payouts: Map<string, Payout> = new Map();
  protected reservations: Map<string, Reservation> = new Map();
  protected promos: Map<string, Promo> = new Map();
  protected notifications: Map<string, Notification> = new Map();
  protected earnings: Map<string, Earning> = new Map();
  protected attributes: Map<string, Attribute> = new Map();
  protected marketingCampaigns: Map<string, MarketingCampaign> = new Map();
  protected paymentGateways: Map<string, PaymentGateway> = new Map();
  protected upiTransactions: Map<string, UpiTransaction> = new Map();
  protected razorpayTransactions: Map<string, RazorpayTransaction> = new Map();
  protected categories: Map<string, {id: string; merchantId: string; name: string; isActive: boolean; sortOrder: number}> = new Map();
  protected subUsers: Map<string, {id: string; parentType: string; parentId: string; name: string; email: string; phone?: string; username: string; passwordHash: string; isActive: boolean; permissions: string[]; lastLogin?: Date; createdAt: Date; updatedAt: Date}> = new Map();
  protected freshMilkRoutesMap: Map<string, FreshMilkRoute> = new Map();
  protected freshMilkDispatches: Map<string, FreshMilkDispatch> = new Map();
  protected freshMilkDispatchItems: Map<string, FreshMilkDispatchItem> = new Map();
  protected freshMilkReturns: Map<string, FreshMilkReturn> = new Map();

  constructor() {
    this.seedData();
    this.seedAdminUserSync().catch(err => console.error('Failed to seed admin users:', err));
    this.seedKarenderiaData();
  }

  protected seedData() {
    // Seed AAVIN District Union dairy outlets
    // District Unions based on TCMPF structure (27 District Unions + 4 Federation Dairies)
    // Note: Chennai is NOT a District Union - it's covered by Federation Dairies
    const sampleRestaurants: Restaurant[] = [
      {
        id: "UNI-CBE-01",
        name: "AAVIN Coimbatore Union",
        description: "Coimbatore District Cooperative Milk Producers Union Ltd - Premium dairy products",
        cuisine: "Milk",
        image: "/unions/dairy-factory-1_2.jpg",
        rating: "4.7",
        deliveryTime: "25-40 min",
        deliveryFee: "0.00",
        address: "Perur Road, Coimbatore - 641010",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "UNI-SLM-01",
        name: "AAVIN Salem Union",
        description: "Salem District Cooperative Milk Producers Union Ltd - Milk, paneer, ghee",
        cuisine: "Milk",
        image: "/salem-union-card.png",
        rating: "4.6",
        deliveryTime: "30-45 min",
        deliveryFee: "0.00",
        address: "Sithanur, Thalavaippatty, Salem - 636302",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "UNI-MDU-01",
        name: "AAVIN Madurai Union",
        description: "Madurai District Cooperative Milk Producers Union Ltd - Traditional sweets and dairy",
        cuisine: "Milk",
        image: "/unions/dairy-factory-1_4.jpg",
        rating: "4.9",
        deliveryTime: "25-35 min",
        deliveryFee: "0.00",
        address: "Thirunagar, Madurai - 625006",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "UNI-TRY-01",
        name: "AAVIN Trichy Union",
        description: "Trichy District Cooperative Milk Producers Union Ltd - Butter, curd, buttermilk",
        cuisine: "Milk",
        image: "/unions/dairy-factory-1_5.jpg",
        rating: "4.5",
        deliveryTime: "30-40 min",
        deliveryFee: "0.00",
        address: "Woraiyur, Tiruchirappalli - 620003",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "UNI-TNJ-01",
        name: "AAVIN Thanjavur Union",
        description: "Thanjavur District Cooperative Milk Producers Union Ltd - Ghee and traditional products",
        cuisine: "Milk",
        image: "/unions/dairy-factory-6_1.jpg",
        rating: "4.8",
        deliveryTime: "35-45 min",
        deliveryFee: "0.00",
        address: "Kumbakonam Road, Thanjavur - 613001",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "UNI-ERO-01",
        name: "AAVIN Erode Union",
        description: "Erode District Cooperative Milk Producers Union Ltd - Fresh milk and curd",
        cuisine: "Milk",
        image: "/unions/dairy-factory-6_2.jpg",
        rating: "4.6",
        deliveryTime: "30-40 min",
        deliveryFee: "0.00",
        address: "Bhavani Road, Erode - 638001",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "UNI-TNV-01",
        name: "AAVIN Tirunelveli Union",
        description: "Tirunelveli District Cooperative Milk Producers Union Ltd - Ice cream and frozen desserts",
        cuisine: "Milk",
        image: "/unions/dairy-factory-6_3.jpg",
        rating: "4.7",
        deliveryTime: "25-35 min",
        deliveryFee: "0.00",
        address: "Palayamkottai, Tirunelveli - 627002",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "UNI-VLR-01",
        name: "AAVIN Vellore Union",
        description: "Vellore District Cooperative Milk Producers Union Ltd - Premium dairy range",
        cuisine: "Milk",
        image: "/unions/dairy-factory-6_4.jpg",
        rating: "4.5",
        deliveryTime: "30-45 min",
        deliveryFee: "0.00",
        address: "Sathuvachari, Vellore - 632009",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "UNI-VPM-01",
        name: "AAVIN Villupuram Union",
        description: "Villupuram District Cooperative Milk Producers Union Ltd - Buttermilk specialists",
        cuisine: "Milk",
        image: "/unions/dairy-factory-6_5.jpg",
        rating: "4.4",
        deliveryTime: "35-50 min",
        deliveryFee: "0.00",
        address: "Tindivanam Road, Villupuram - 605602",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "UNI-KTU-01",
        name: "AAVIN Kanchipuram-Thiruvallur Union",
        description: "Kanchipuram-Thiruvallur District Cooperative Milk Producers Union Ltd",
        cuisine: "Milk",
        image: "/unions/dairy-factory-1_1.jpg",
        rating: "4.6",
        deliveryTime: "25-40 min",
        deliveryFee: "0.00",
        address: "GST Road, Kancheepuram - 631501",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "UNI-TVM-01",
        name: "AAVIN Thiruvannamalai Union",
        description: "Thiruvannamalai District Cooperative Milk Producers Union Ltd - Traditional dairy",
        cuisine: "Milk",
        image: "/unions/dairy-factory-1_2.jpg",
        rating: "4.5",
        deliveryTime: "35-45 min",
        deliveryFee: "0.00",
        address: "Polur Road, Tiruvannamalai - 606601",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "UNI-CUD-01",
        name: "AAVIN Cuddalore Union",
        description: "Cuddalore District Cooperative Milk Producers Union Ltd - Quality assured products",
        cuisine: "Milk",
        image: "/unions/dairy-factory-1_4.jpg",
        rating: "4.4",
        deliveryTime: "30-45 min",
        deliveryFee: "0.00",
        address: "Chidambaram Road, Cuddalore - 607001",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "UNI-DGL-01",
        name: "AAVIN Dindigul Union",
        description: "Dindigul District Cooperative Milk Producers Union Ltd - Famous for dairy products",
        cuisine: "Milk",
        image: "/unions/dairy-factory-1_5.jpg",
        rating: "4.8",
        deliveryTime: "25-35 min",
        deliveryFee: "0.00",
        address: "Palani Road, Dindigul - 624001",
        isOpen: true,
        createdAt: new Date(),
      },
      // Federation Dairies (Chennai area)
      {
        id: "FED-MAD-01",
        name: "Madhavaram Dairy",
        description: "Federation Dairy - Madhavaram, Chennai",
        cuisine: "Milk",
        image: "/unions/dairy-factory-1_1.jpg",
        rating: "4.8",
        deliveryTime: "30-45 min",
        deliveryFee: "0.00",
        address: "Madhavaram Milk Colony, Chennai - 600051",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "FED-AMB-01",
        name: "Ambattur Dairy",
        description: "Federation Dairy - Ambattur, Chennai",
        cuisine: "Milk",
        image: "/unions/dairy-factory-1_2.jpg",
        rating: "4.7",
        deliveryTime: "25-40 min",
        deliveryFee: "0.00",
        address: "Ambattur Industrial Estate, Chennai - 600058",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "FED-SHL-01",
        name: "Sholinganallur Dairy",
        description: "Federation Dairy - Sholinganallur, Chennai",
        cuisine: "Milk",
        image: "/unions/dairy-factory-1_5.jpg",
        rating: "4.6",
        deliveryTime: "30-40 min",
        deliveryFee: "0.00",
        address: "Sholinganallur, Chennai - 600119",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "UNI-THN-01",
        name: "AAVIN Theni Union",
        description: "Theni District Cooperative Milk Producers Union Ltd - Hill station fresh dairy",
        cuisine: "Milk",
        image: "/unions/dairy-factory-6_1.jpg",
        rating: "4.7",
        deliveryTime: "30-40 min",
        deliveryFee: "0.00",
        address: "Periyakulam Road, Theni - 625531",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "UNI-VNR-01",
        name: "AAVIN Virudhunagar Union",
        description: "Virudhunagar District Cooperative Milk Producers Union Ltd - Traditional quality",
        cuisine: "Milk",
        image: "/unions/dairy-factory-6_2.jpg",
        rating: "4.5",
        deliveryTime: "30-45 min",
        deliveryFee: "0.00",
        address: "Sivakasi Road, Virudhunagar - 626001",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "UNI-SVG-01",
        name: "AAVIN Sivagangai Union",
        description: "Sivagangai District Cooperative Milk Producers Union Ltd - Heritage dairy traditions",
        cuisine: "Milk",
        image: "/unions/dairy-factory-6_4.jpg",
        rating: "4.5",
        deliveryTime: "30-45 min",
        deliveryFee: "0.00",
        address: "Karaikudi Road, Sivaganga - 630561",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "UNI-TUT-01",
        name: "AAVIN Thoothukudi Union",
        description: "Thoothukudi District Cooperative Milk Producers Union Ltd - Port city dairy hub",
        cuisine: "Milk",
        image: "/unions/dairy-factory-6_5.jpg",
        rating: "4.6",
        deliveryTime: "25-35 min",
        deliveryFee: "0.00",
        address: "Palayamkottai Road, Thoothukudi - 628002",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "UNI-KYK-01",
        name: "AAVIN Kanyakumari Union",
        description: "Kanyakumari District Cooperative Milk Producers Union Ltd - Southernmost dairy",
        cuisine: "Milk",
        image: "/unions/dairy-factory-1_1.jpg",
        rating: "4.5",
        deliveryTime: "35-50 min",
        deliveryFee: "0.00",
        address: "Nagercoil Road, Kanyakumari - 629001",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "UNI-NKL-01",
        name: "AAVIN Namakkal Union",
        description: "Namakkal District Cooperative Milk Producers Union Ltd - Poultry belt dairy",
        cuisine: "Milk",
        image: "/unions/dairy-factory-1_2.jpg",
        rating: "4.6",
        deliveryTime: "30-40 min",
        deliveryFee: "0.00",
        address: "Tiruchengode Road, Namakkal - 637001",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "UNI-DPI-01",
        name: "AAVIN Dharmapuri Union",
        description: "Dharmapuri District Cooperative Milk Producers Union Ltd - Hill region dairy",
        cuisine: "Milk",
        image: "/unions/dairy-factory-1_2.jpg",
        rating: "4.4",
        deliveryTime: "35-50 min",
        deliveryFee: "0.00",
        address: "Krishnagiri Road, Dharmapuri - 636701",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "UNI-KGI-01",
        name: "AAVIN Krishnagiri Union",
        description: "Krishnagiri District Cooperative Milk Producers Union Ltd - Mango belt dairy",
        cuisine: "Milk",
        image: "/unions/dairy-factory-1_4.jpg",
        rating: "4.5",
        deliveryTime: "30-45 min",
        deliveryFee: "0.00",
        address: "Hosur Road, Krishnagiri - 635001",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "UNI-TPR-01",
        name: "AAVIN Tirupur Union",
        description: "Tirupur District Cooperative Milk Producers Union Ltd - Textile city dairy",
        cuisine: "Milk",
        image: "/unions/dairy-factory-1_5.jpg",
        rating: "4.6",
        deliveryTime: "25-35 min",
        deliveryFee: "0.00",
        address: "Avinashi Road, Tiruppur - 641601",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "UNI-KRR-01",
        name: "AAVIN Karur Union",
        description: "Karur District Cooperative Milk Producers Union Ltd - Central TN dairy hub",
        cuisine: "Milk",
        image: "/unions/dairy-factory-6_1.jpg",
        rating: "4.5",
        deliveryTime: "30-40 min",
        deliveryFee: "0.00",
        address: "Trichy Road, Karur - 639001",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "UNI-PUD-01",
        name: "AAVIN Pudukkottai Union",
        description: "Pudukkottai District Cooperative Milk Producers Union Ltd - Heritage dairy",
        cuisine: "Milk",
        image: "/unions/dairy-factory-6_2.jpg",
        rating: "4.4",
        deliveryTime: "35-50 min",
        deliveryFee: "0.00",
        address: "Trichy Road, Pudukkottai - 622001",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "UNI-NGR-01",
        name: "AAVIN Nilgiris Union",
        description: "Nilgiris District Cooperative Milk Producers Union Ltd - Hill station dairy",
        cuisine: "Milk",
        image: "/unions/dairy-factory-6_3.jpg",
        rating: "4.7",
        deliveryTime: "30-45 min",
        deliveryFee: "0.00",
        address: "Coonoor Road, Ooty - 643001",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "UNI-KAL-01",
        name: "AAVIN Kallakurichi Union",
        description: "Kallakurichi District Cooperative Milk Producers Union Ltd - New district dairy",
        cuisine: "Milk",
        image: "/unions/dairy-factory-6_4.jpg",
        rating: "4.3",
        deliveryTime: "35-50 min",
        deliveryFee: "0.00",
        address: "Sankarapuram Road, Kallakurichi - 606202",
        isOpen: true,
        createdAt: new Date(),
      },
      {
        id: "UNI-TPT-01",
        name: "AAVIN Thirupathur Union",
        description: "Thirupathur District Cooperative Milk Producers Union Ltd",
        cuisine: "Milk",
        image: "/unions/dairy-factory-6_5.jpg",
        rating: "4.4",
        deliveryTime: "30-45 min",
        deliveryFee: "0.00",
        address: "Vaniyambadi Road, Thirupathur - 635601",
        isOpen: true,
        createdAt: new Date(),
      },
      // Products Dairy (Federation)
      {
        id: "FED-PROD-01",
        name: "Products Dairy (Ambattur)",
        description: "Federation Products Dairy - All dairy products",
        cuisine: "Milk",
        image: "/unions/dairy-factory-1_4.jpg",
        rating: "4.8",
        deliveryTime: "30-45 min",
        deliveryFee: "0.00",
        address: "Ambattur Industrial Estate, Chennai - 600058",
        isOpen: true,
        createdAt: new Date(),
      },
    ];

    sampleRestaurants.forEach(restaurant => {
      this.restaurants.set(restaurant.id, restaurant);
    });

    // Seed menu items for Salem Union (Salem customers like Nagaas Retail should see Salem products)
    // Salem District Cooperative Milk Producers' Union (SDCMPU) Products
    const sampleMenuItems: MenuItem[] = [
      // Price Chart effective 01.12.2025 to 28.02.2026
      {
        id: "slm-001",
        restaurantId: "UNI-SLM-01",
        name: "Cooking Butter 100gm",
        description: "Premium quality cooking butter - GST 5%",
        price: "60.00",
        category: "Butter",
        image: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-BTR-001",
        subcategory: "Cooking Butter",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "48.48",
        districtUnionPrice: "48.48",
        wholesalePrice: "50.88",
        retailPrice: "57.14",
        retailerPrice: null,
        mrp: "60.00",
        unitSize: "100",
        unitType: "gm",
        productSegment: "Products",
        packagingType: "box",
        unitsPerPackage: 100,
        packageWeight: "10.00",
        packageWeightUnit: "kgs",
      },
      {
        id: "slm-002",
        restaurantId: "UNI-SLM-01",
        name: "Cooking Butter 500gm",
        description: "Premium quality cooking butter - GST 5%",
        price: "275.00",
        category: "Butter",
        image: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-BTR-002",
        subcategory: "Cooking Butter",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "222.16",
        districtUnionPrice: "222.16",
        wholesalePrice: "244.84",
        retailPrice: "261.90",
        retailerPrice: null,
        mrp: "275.00",
        unitSize: "500",
        unitType: "gm",
        productSegment: "Products",
        packagingType: "box",
        unitsPerPackage: 20,
        packageWeight: "10.00",
        packageWeightUnit: "kgs",
      },
      {
        id: "slm-003",
        restaurantId: "UNI-SLM-01",
        name: "Tasting Butter 100gm",
        description: "Premium quality table butter - GST 5%",
        price: "60.00",
        category: "Butter",
        image: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-BTR-003",
        subcategory: "Tasting Butter",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "48.48",
        districtUnionPrice: "48.48",
        wholesalePrice: "53.42",
        retailPrice: "57.14",
        retailerPrice: null,
        mrp: "60.00",
        unitSize: "100",
        unitType: "gm",
        productSegment: "Products",
        packagingType: "box",
        unitsPerPackage: 100,
        packageWeight: "10.00",
        packageWeightUnit: "kgs",
      },
      {
        id: "slm-004",
        restaurantId: "UNI-SLM-01",
        name: "Tasting Butter 500gm",
        description: "Premium quality table butter - GST 5%",
        price: "280.00",
        category: "Butter",
        image: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-BTR-004",
        subcategory: "Tasting Butter",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "226.19",
        districtUnionPrice: "237.42",
        wholesalePrice: "249.29",
        retailPrice: "266.67",
        retailerPrice: null,
        mrp: "280.00",
        unitSize: "500",
        unitType: "gm",
        productSegment: "Products",
        packagingType: "box",
        unitsPerPackage: 20,
        packageWeight: "10.00",
        packageWeightUnit: "kgs",
      },
      {
        id: "slm-005",
        restaurantId: "UNI-SLM-01",
        name: "Ghee 15ml Pouch",
        description: "Pure cow ghee sachet - GST 5%",
        price: "12.00",
        category: "Ghee",
        image: "https://images.unsplash.com/photo-1625938145744-e380515399bf?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-GHE-001",
        subcategory: "Ghee Pouch",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "10.26",
        districtUnionPrice: "10.64",
        wholesalePrice: "10.90",
        retailPrice: "11.43",
        retailerPrice: null,
        mrp: "12.00",
        unitSize: "15",
        unitType: "ml",
        productSegment: "Products",
        packagingType: "box",
        unitsPerPackage: 100,
        packageWeight: "10.00",
        packageWeightUnit: "lit",
      },
      {
        id: "slm-006",
        restaurantId: "UNI-SLM-01",
        name: "Ghee 50ml Jar",
        description: "Pure cow ghee in glass jar - GST 5%",
        price: "48.00",
        category: "Ghee",
        image: "https://images.unsplash.com/photo-1625938145744-e380515399bf?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-GHE-002",
        subcategory: "Ghee Jar",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "40.24",
        districtUnionPrice: "41.91",
        wholesalePrice: "43.07",
        retailPrice: "45.71",
        retailerPrice: null,
        mrp: "48.00",
        unitSize: "50",
        unitType: "ml",
        productSegment: "Products",
        packagingType: "box",
        unitsPerPackage: 100,
        packageWeight: "10.00",
        packageWeightUnit: "lit",
      },
      {
        id: "slm-007",
        restaurantId: "UNI-SLM-01",
        name: "Ghee 100ml Pouch",
        description: "Pure cow ghee sachet - GST 5%",
        price: "80.00",
        category: "Ghee",
        image: "https://images.unsplash.com/photo-1625938145744-e380515399bf?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-GHE-003",
        subcategory: "Ghee Pouch",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "67.03",
        districtUnionPrice: "69.82",
        wholesalePrice: "71.77",
        retailPrice: "74.43",
        retailerPrice: null,
        mrp: "80.00",
        unitSize: "100",
        unitType: "ml",
        productSegment: "Products",
        packagingType: "box",
        unitsPerPackage: 100,
        packageWeight: "10.00",
        packageWeightUnit: "lit",
      },
      {
        id: "slm-008",
        restaurantId: "UNI-SLM-01",
        name: "Ghee 100ml Jar",
        description: "Pure cow ghee in glass jar - GST 5%",
        price: "85.00",
        category: "Ghee",
        image: "https://images.unsplash.com/photo-1625938145744-e380515399bf?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-GHE-004",
        subcategory: "Ghee Jar",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "71.19",
        districtUnionPrice: "74.17",
        wholesalePrice: "76.25",
        retailPrice: "80.95",
        retailerPrice: null,
        mrp: "85.00",
        unitSize: "100",
        unitType: "ml",
        productSegment: "Products",
        packagingType: "box",
        unitsPerPackage: 50,
        packageWeight: "10.00",
        packageWeightUnit: "lit",
      },
      {
        id: "slm-009",
        restaurantId: "UNI-SLM-01",
        name: "Ghee 200ml Jar",
        description: "Pure cow ghee in glass jar - GST 5%",
        price: "160.00",
        category: "Ghee",
        image: "https://images.unsplash.com/photo-1625938145744-e380515399bf?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-GHE-005",
        subcategory: "Ghee Jar",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "134.07",
        districtUnionPrice: "139.66",
        wholesalePrice: "143.55",
        retailPrice: "152.38",
        retailerPrice: null,
        mrp: "160.00",
        unitSize: "200",
        unitType: "ml",
        productSegment: "Products",
        packagingType: "box",
        unitsPerPackage: 20,
        packageWeight: "10.00",
        packageWeightUnit: "lit",
      },
      {
        id: "slm-010",
        restaurantId: "UNI-SLM-01",
        name: "Ghee 500ml Jar",
        description: "Pure cow ghee in glass jar - GST 5%",
        price: "365.00",
        category: "Ghee",
        image: "https://images.unsplash.com/photo-1625938145744-e380515399bf?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-GHE-006",
        subcategory: "Ghee Jar",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "305.38",
        districtUnionPrice: "318.22",
        wholesalePrice: "327.17",
        retailPrice: "347.62",
        retailerPrice: null,
        mrp: "365.00",
        unitSize: "500",
        unitType: "ml",
        productSegment: "Products",
        packagingType: "box",
        unitsPerPackage: 20,
        packageWeight: "10.00",
        packageWeightUnit: "lit",
      },
      {
        id: "slm-011",
        restaurantId: "UNI-SLM-01",
        name: "Ghee 500ml Jar (Carton)",
        description: "Pure cow ghee carton pack - GST 5%",
        price: "360.00",
        category: "Ghee",
        image: "https://images.unsplash.com/photo-1625938145744-e380515399bf?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-GHE-007",
        subcategory: "Ghee Carton",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "301.26",
        districtUnionPrice: "313.92",
        wholesalePrice: "322.74",
        retailPrice: "342.86",
        retailerPrice: null,
        mrp: "360.00",
        unitSize: "500",
        unitType: "ml",
        productSegment: "Products",
        packagingType: "box",
        unitsPerPackage: 20,
        packageWeight: "10.00",
        packageWeightUnit: "lit",
      },
      {
        id: "slm-012",
        restaurantId: "UNI-SLM-01",
        name: "Ghee 1lt Jar",
        description: "Pure cow ghee in glass jar - GST 5%",
        price: "700.00",
        category: "Ghee",
        image: "https://images.unsplash.com/photo-1625938145744-e380515399bf?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-GHE-008",
        subcategory: "Ghee Jar",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "585.93",
        districtUnionPrice: "610.50",
        wholesalePrice: "627.62",
        retailPrice: "666.67",
        retailerPrice: null,
        mrp: "700.00",
        unitSize: "1",
        unitType: "lt",
        productSegment: "Products",
        packagingType: "box",
        unitsPerPackage: 2,
        packageWeight: "10.00",
        packageWeightUnit: "lit",
      },
      {
        id: "slm-013",
        restaurantId: "UNI-SLM-01",
        name: "Ghee 1lt Jar (Carton)",
        description: "Pure cow ghee carton pack - GST 5%",
        price: "690.00",
        category: "Ghee",
        image: "https://images.unsplash.com/photo-1625938145744-e380515399bf?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-GHE-009",
        subcategory: "Ghee Carton",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "577.65",
        districtUnionPrice: "601.84",
        wholesalePrice: "618.69",
        retailPrice: "657.14",
        retailerPrice: null,
        mrp: "690.00",
        unitSize: "1",
        unitType: "lt",
        productSegment: "Products",
        packagingType: "box",
        unitsPerPackage: 2,
        packageWeight: "10.00",
        packageWeightUnit: "lit",
      },
      {
        id: "slm-014",
        restaurantId: "UNI-SLM-01",
        name: "Ghee 5lt Petjar",
        description: "Pure cow ghee bulk pack - GST 5%",
        price: "3600.00",
        category: "Ghee",
        image: "https://images.unsplash.com/photo-1625938145744-e380515399bf?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-GHE-010",
        subcategory: "Ghee Bulk",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "3038.30",
        districtUnionPrice: "3159.27",
        wholesalePrice: "3243.54",
        retailPrice: "3428.57",
        retailerPrice: null,
        mrp: "3600.00",
        unitSize: "5",
        unitType: "lt",
        productSegment: "Products",
        packagingType: "box",
        unitsPerPackage: 2,
        packageWeight: "10.00",
        packageWeightUnit: "lit",
      },
      {
        id: "slm-015",
        restaurantId: "UNI-SLM-01",
        name: "Ghee 15kg Tin",
        description: "Pure cow ghee bulk tin - GST 5%",
        price: "11880.00",
        category: "Ghee",
        image: "https://images.unsplash.com/photo-1625938145744-e380515399bf?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-GHE-011",
        subcategory: "Ghee Bulk",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "10026.28",
        districtUnionPrice: "10425.49",
        wholesalePrice: "10703.61",
        retailPrice: "11314.29",
        retailerPrice: null,
        mrp: "11880.00",
        unitSize: "15",
        unitType: "kg",
        productSegment: "Products",
        packagingType: "tin",
        unitsPerPackage: 1,
        packageWeight: "1.00",
        packageWeightUnit: "nos",
      },
      {
        id: "slm-016",
        restaurantId: "UNI-SLM-01",
        name: "S.M. Powder 1kg",
        description: "Skimmed milk powder - GST 5%",
        price: "420.00",
        category: "Milk",
        image: "https://images.unsplash.com/photo-1563636619-e9143da7973b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-SMP-001",
        subcategory: "Milk Powder",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "339.44",
        districtUnionPrice: "339.44",
        wholesalePrice: "367.13",
        retailPrice: "400.00",
        retailerPrice: null,
        mrp: "420.00",
        unitSize: "1",
        unitType: "kg",
        productSegment: "Products",
        packagingType: "bag",
        unitsPerPackage: 15,
        packageWeight: "15.00",
        packageWeightUnit: "kgs",
      },
      {
        id: "slm-017",
        restaurantId: "UNI-SLM-01",
        name: "S.M. Powder 500gm",
        description: "Skimmed milk powder - GST 5%",
        price: "210.00",
        category: "Milk",
        image: "https://images.unsplash.com/photo-1563636619-e9143da7973b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-SMP-002",
        subcategory: "Milk Powder",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "169.70",
        districtUnionPrice: "169.70",
        wholesalePrice: "183.55",
        retailPrice: "190.89",
        retailerPrice: null,
        mrp: "210.00",
        unitSize: "500",
        unitType: "gm",
        productSegment: "Products",
        packagingType: "bag",
        unitsPerPackage: 30,
        packageWeight: "15.00",
        packageWeightUnit: "kgs",
      },
      {
        id: "slm-018",
        restaurantId: "UNI-SLM-01",
        name: "FM Tetra 200ml",
        description: "Flavoured milk tetra pack - GST 5%",
        price: "30.00",
        category: "Milk",
        image: "https://images.unsplash.com/photo-1563636619-e9143da7973b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-FLV-001",
        subcategory: "Flavoured Milk",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "22.08",
        districtUnionPrice: "22.08",
        wholesalePrice: "24.47",
        retailPrice: "28.57",
        retailerPrice: null,
        mrp: "30.00",
        unitSize: "200",
        unitType: "ml",
        productSegment: "Products",
        packagingType: "tray",
        unitsPerPackage: 27,
        packageWeight: null,
        packageWeightUnit: "nos",
      },
      {
        id: "slm-019",
        restaurantId: "UNI-SLM-01",
        name: "Milk Shake 200ml",
        description: "Flavoured milk shake tetra pack - GST 5%",
        price: "30.00",
        category: "Milk",
        image: "https://images.unsplash.com/photo-1563636619-e9143da7973b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-FLV-002",
        subcategory: "Flavoured Milk",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "22.08",
        districtUnionPrice: "22.08",
        wholesalePrice: "24.47",
        retailPrice: "25.44",
        retailerPrice: null,
        mrp: "30.00",
        unitSize: "200",
        unitType: "ml",
        productSegment: "Products",
        packagingType: "tray",
        unitsPerPackage: 27,
        packageWeight: null,
        packageWeightUnit: "nos",
      },
      {
        id: "slm-020",
        restaurantId: "UNI-SLM-01",
        name: "Maavin 200ml",
        description: "Mango flavoured milk - GST 5%",
        price: "20.00",
        category: "Milk",
        image: "https://images.unsplash.com/photo-1563636619-e9143da7973b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-FLV-003",
        subcategory: "Flavoured Milk",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "15.09",
        districtUnionPrice: "15.09",
        wholesalePrice: "16.32",
        retailPrice: "19.05",
        retailerPrice: null,
        mrp: "20.00",
        unitSize: "200",
        unitType: "ml",
        productSegment: "Products",
        packagingType: "tray",
        unitsPerPackage: 27,
        packageWeight: null,
        packageWeightUnit: "nos",
      },
      {
        id: "slm-021",
        restaurantId: "UNI-SLM-01",
        name: "SM Tetra 1000ml",
        description: "Standardized milk tetra pack - GST 0%",
        price: "75.00",
        category: "Milk",
        image: "https://images.unsplash.com/photo-1563636619-e9143da7973b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-MLK-001",
        subcategory: "Tetra Milk",
        hsnCode: null,
        gstPercent: "0.00",
        federationPrice: "62.94",
        districtUnionPrice: "62.94",
        wholesalePrice: "67.42",
        retailPrice: "69.44",
        retailerPrice: null,
        mrp: "75.00",
        unitSize: "1000",
        unitType: "ml",
        productSegment: "Products",
        packagingType: "box",
        unitsPerPackage: 12,
        packageWeight: null,
        packageWeightUnit: "nos",
      },
      {
        id: "slm-022",
        restaurantId: "UNI-SLM-01",
        name: "TM Tetra 1000ml",
        description: "Toned milk tetra pack - GST 0%",
        price: "65.00",
        category: "Milk",
        image: "https://images.unsplash.com/photo-1563636619-e9143da7973b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-MLK-002",
        subcategory: "Tetra Milk",
        hsnCode: null,
        gstPercent: "0.00",
        federationPrice: "54.54",
        districtUnionPrice: "54.54",
        wholesalePrice: "58.43",
        retailPrice: "60.18",
        retailerPrice: null,
        mrp: "65.00",
        unitSize: "1000",
        unitType: "ml",
        productSegment: "Products",
        packagingType: "box",
        unitsPerPackage: 12,
        packageWeight: null,
        packageWeightUnit: "nos",
      },
      {
        id: "slm-023",
        restaurantId: "UNI-SLM-01",
        name: "Khova 50gm",
        description: "Traditional milk solid - GST 5%",
        price: "25.00",
        category: "Sweets",
        image: "https://images.unsplash.com/photo-1605197161470-5f2ad2e2b506?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-KHV-001",
        subcategory: "Khova",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "20.62",
        districtUnionPrice: "20.62",
        wholesalePrice: "21.65",
        retailPrice: "23.81",
        retailerPrice: null,
        mrp: "25.00",
        unitSize: "50",
        unitType: "gm",
        productSegment: "Products",
        packagingType: "box",
        unitsPerPackage: 100,
        packageWeight: "5.00",
        packageWeightUnit: "kgs",
      },
      {
        id: "slm-024",
        restaurantId: "UNI-SLM-01",
        name: "Khova 250gm",
        description: "Traditional milk solid - GST 5%",
        price: "130.00",
        category: "Sweets",
        image: "https://images.unsplash.com/photo-1605197161470-5f2ad2e2b506?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-KHV-002",
        subcategory: "Khova",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "107.18",
        districtUnionPrice: "107.18",
        wholesalePrice: "112.54",
        retailPrice: "123.81",
        retailerPrice: null,
        mrp: "130.00",
        unitSize: "250",
        unitType: "gm",
        productSegment: "Products",
        packagingType: "box",
        unitsPerPackage: 20,
        packageWeight: "5.00",
        packageWeightUnit: "kgs",
      },
      {
        id: "slm-025",
        restaurantId: "UNI-SLM-01",
        name: "Unsugared Khova 1kg",
        description: "Plain khova without sugar - GST 5%",
        price: "600.00",
        category: "Sweets",
        image: "https://images.unsplash.com/photo-1605197161470-5f2ad2e2b506?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-KHV-003",
        subcategory: "Khova",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "494.72",
        districtUnionPrice: "494.72",
        wholesalePrice: "519.46",
        retailPrice: "571.43",
        retailerPrice: null,
        mrp: "600.00",
        unitSize: "1",
        unitType: "kg",
        productSegment: "Products",
        packagingType: "box",
        unitsPerPackage: 1,
        packageWeight: "1.00",
        packageWeightUnit: "kgs",
      },
      {
        id: "slm-026",
        restaurantId: "UNI-SLM-01",
        name: "250gm Special Mysorepa",
        description: "Premium mysore pak sweet - GST 5%",
        price: "140.00",
        category: "Sweets",
        image: "https://images.unsplash.com/photo-1605197161470-5f2ad2e2b506?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-SWT-001",
        subcategory: "Mysore Pak",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "115.44",
        districtUnionPrice: "115.44",
        wholesalePrice: "121.21",
        retailPrice: "133.33",
        retailerPrice: null,
        mrp: "140.00",
        unitSize: "250",
        unitType: "gm",
        productSegment: "Products",
        packagingType: "box",
        unitsPerPackage: 20,
        packageWeight: "5.00",
        packageWeightUnit: "kgs",
      },
      {
        id: "slm-027",
        restaurantId: "UNI-SLM-01",
        name: "250gm Carrot Mysorepa",
        description: "Carrot flavoured mysore pak - GST 5%",
        price: "140.00",
        category: "Sweets",
        image: "https://images.unsplash.com/photo-1605197161470-5f2ad2e2b506?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-SWT-002",
        subcategory: "Mysore Pak",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "115.44",
        districtUnionPrice: "115.44",
        wholesalePrice: "121.21",
        retailPrice: "127.27",
        retailerPrice: null,
        mrp: "140.00",
        unitSize: "250",
        unitType: "gm",
        productSegment: "Products",
        packagingType: "box",
        unitsPerPackage: 20,
        packageWeight: "5.00",
        packageWeightUnit: "kgs",
      },
      {
        id: "slm-028",
        restaurantId: "UNI-SLM-01",
        name: "250gm Milk Cake",
        description: "Traditional milk cake sweet - GST 5%",
        price: "140.00",
        category: "Sweets",
        image: "https://images.unsplash.com/photo-1605197161470-5f2ad2e2b506?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-SWT-003",
        subcategory: "Milk Cake",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "115.44",
        districtUnionPrice: "115.44",
        wholesalePrice: "121.21",
        retailPrice: "127.33",
        retailerPrice: null,
        mrp: "140.00",
        unitSize: "250",
        unitType: "gm",
        productSegment: "Products",
        packagingType: "box",
        unitsPerPackage: 20,
        packageWeight: "5.00",
        packageWeightUnit: "kgs",
      },
      {
        id: "slm-029",
        restaurantId: "UNI-SLM-01",
        name: "250gm Cashew Cake",
        description: "Premium cashew cake sweet - GST 5%",
        price: "185.00",
        category: "Sweets",
        image: "https://images.unsplash.com/photo-1605197161470-5f2ad2e2b506?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-SWT-004",
        subcategory: "Cashew Cake",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "152.53",
        districtUnionPrice: "152.53",
        wholesalePrice: "160.16",
        retailPrice: "176.18",
        retailerPrice: null,
        mrp: "185.00",
        unitSize: "250",
        unitType: "gm",
        productSegment: "Products",
        packagingType: "box",
        unitsPerPackage: 20,
        packageWeight: "5.00",
        packageWeightUnit: "kgs",
      },
      {
        id: "slm-030",
        restaurantId: "UNI-SLM-01",
        name: "Badam Mix Powder 200gm",
        description: "Almond milk powder mix - GST 5%",
        price: "120.00",
        category: "Beverages",
        image: "https://images.unsplash.com/photo-1563636619-e9143da7973b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-BDM-001",
        subcategory: "Badam Mix",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "90.81",
        districtUnionPrice: "90.81",
        wholesalePrice: "101.94",
        retailPrice: "114.29",
        retailerPrice: null,
        mrp: "120.00",
        unitSize: "200",
        unitType: "gm",
        productSegment: "Products",
        packagingType: "box",
        unitsPerPackage: 25,
        packageWeight: "5.00",
        packageWeightUnit: "kgs",
      },
      {
        id: "slm-031",
        restaurantId: "UNI-SLM-01",
        name: "500gm Paneer",
        description: "Fresh cottage cheese - GST 0%",
        price: "275.00",
        category: "Paneer",
        image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-PNR-001",
        subcategory: "Fresh Paneer",
        hsnCode: null,
        gstPercent: "0.00",
        federationPrice: "192.91",
        districtUnionPrice: "192.91",
        wholesalePrice: "208.34",
        retailPrice: "229.17",
        retailerPrice: null,
        mrp: "275.00",
        unitSize: "500",
        unitType: "gm",
        productSegment: "Products",
        packagingType: "box",
        unitsPerPackage: 25,
        packageWeight: "5.00",
        packageWeightUnit: "kgs",
      },
      {
        id: "slm-032",
        restaurantId: "UNI-SLM-01",
        name: "200gm Paneer",
        description: "Fresh cottage cheese - GST 0%",
        price: "110.00",
        category: "Paneer",
        image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-PNR-002",
        subcategory: "Fresh Paneer",
        hsnCode: null,
        gstPercent: "0.00",
        federationPrice: "77.18",
        districtUnionPrice: "77.18",
        wholesalePrice: "83.35",
        retailPrice: "91.69",
        retailerPrice: null,
        mrp: "110.00",
        unitSize: "200",
        unitType: "gm",
        productSegment: "Products",
        packagingType: "box",
        unitsPerPackage: 25,
        packageWeight: "5.00",
        packageWeightUnit: "kgs",
      },
      {
        id: "slm-033",
        restaurantId: "UNI-SLM-01",
        name: "Buttermilk 150ml Sachet",
        description: "Refreshing spiced buttermilk - GST 5%",
        price: "7.00",
        category: "Buttermilk",
        image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-BTM-001",
        subcategory: "Buttermilk Sachet",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "5.44",
        districtUnionPrice: "5.44",
        wholesalePrice: "5.72",
        retailPrice: "6.00",
        retailerPrice: null,
        mrp: "7.00",
        unitSize: "150",
        unitType: "ml",
        productSegment: "Products",
        packagingType: "tub",
        unitsPerPackage: 60,
        packageWeight: "9.00",
        packageWeightUnit: "lit",
      },
      {
        id: "slm-034",
        restaurantId: "UNI-SLM-01",
        name: "Curd 130gm Sachet",
        description: "Fresh set curd sachet - GST 5%",
        price: "10.00",
        category: "Curd",
        image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-CRD-001",
        subcategory: "Curd Sachet",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "7.62",
        districtUnionPrice: "7.62",
        wholesalePrice: "8.00",
        retailPrice: "9.52",
        retailerPrice: null,
        mrp: "10.00",
        unitSize: "130",
        unitType: "gm",
        productSegment: "Products",
        packagingType: "tub",
        unitsPerPackage: 80,
        packageWeight: "10.00",
        packageWeightUnit: "lit",
      },
      {
        id: "slm-035",
        restaurantId: "UNI-SLM-01",
        name: "Curd 500gm Sachet",
        description: "Fresh set curd large pack - GST 5%",
        price: "31.00",
        category: "Curd",
        image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-CRD-002",
        subcategory: "Curd Pack",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "28.52",
        districtUnionPrice: "28.52",
        wholesalePrice: "29.94",
        retailPrice: "31.00",
        retailerPrice: null,
        mrp: "31.00",
        unitSize: "500",
        unitType: "gm",
        productSegment: "Products",
        packagingType: "tub",
        unitsPerPackage: 20,
        packageWeight: "9.70",
        packageWeightUnit: "lit",
      },
      // Ice Cream Segment Products
      {
        id: "slm-ic-001",
        restaurantId: "UNI-SLM-01",
        name: "Vanilla 50ml Cup",
        description: "Aavin ice cream - Vanilla - GST 5%",
        price: "10.00",
        category: "Ice Cream",
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-ICE-001",
        subcategory: "Ice Cream Cup",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "5.00",
        districtUnionPrice: "5.50",
        wholesalePrice: "6.50",
        retailPrice: "8.50",
        retailerPrice: null,
        mrp: "10.00",
        unitSize: "50",
        unitType: "ml",
        productSegment: "Ice Cream",
        packagingType: "box",
        unitsPerPackage: 32,
        packageWeight: null,
        packageWeightUnit: null,
      },
      {
        id: "slm-ic-002",
        restaurantId: "UNI-SLM-01",
        name: "Mango 50ml Cup",
        description: "Aavin ice cream - Mango - GST 5%",
        price: "10.00",
        category: "Ice Cream",
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-ICE-002",
        subcategory: "Ice Cream Cup",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "5.00",
        districtUnionPrice: "5.50",
        wholesalePrice: "6.50",
        retailPrice: "8.50",
        retailerPrice: null,
        mrp: "10.00",
        unitSize: "50",
        unitType: "ml",
        productSegment: "Ice Cream",
        packagingType: "box",
        unitsPerPackage: 32,
        packageWeight: null,
        packageWeightUnit: null,
      },
      {
        id: "slm-ic-003",
        restaurantId: "UNI-SLM-01",
        name: "Strawberry 50ml Cup",
        description: "Aavin ice cream - Strawberry - GST 5%",
        price: "10.00",
        category: "Ice Cream",
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-ICE-003",
        subcategory: "Ice Cream Cup",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "5.00",
        districtUnionPrice: "5.50",
        wholesalePrice: "6.50",
        retailPrice: "8.50",
        retailerPrice: null,
        mrp: "10.00",
        unitSize: "50",
        unitType: "ml",
        productSegment: "Ice Cream",
        packagingType: "box",
        unitsPerPackage: 32,
        packageWeight: null,
        packageWeightUnit: null,
      },
      {
        id: "slm-ic-004",
        restaurantId: "UNI-SLM-01",
        name: "Choco/Pista 50ml Cup",
        description: "Aavin ice cream - Choco/Pista - GST 5%",
        price: "10.00",
        category: "Ice Cream",
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-ICE-004",
        subcategory: "Ice Cream Cup",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "5.00",
        districtUnionPrice: "5.50",
        wholesalePrice: "6.50",
        retailPrice: "8.50",
        retailerPrice: null,
        mrp: "10.00",
        unitSize: "50",
        unitType: "ml",
        productSegment: "Ice Cream",
        packagingType: "box",
        unitsPerPackage: 32,
        packageWeight: null,
        packageWeightUnit: null,
      },
      {
        id: "slm-ic-005",
        restaurantId: "UNI-SLM-01",
        name: "Kulfi Bar 70ml",
        description: "Aavin ice cream - Kulfi Bar - GST 5%",
        price: "15.00",
        category: "Ice Cream",
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-ICE-005",
        subcategory: "Ice Cream Bar",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "7.50",
        districtUnionPrice: "8.25",
        wholesalePrice: "9.75",
        retailPrice: "12.75",
        retailerPrice: null,
        mrp: "15.00",
        unitSize: "70",
        unitType: "ml",
        productSegment: "Ice Cream",
        packagingType: "box",
        unitsPerPackage: 25,
        packageWeight: null,
        packageWeightUnit: null,
      },
      {
        id: "slm-ic-006",
        restaurantId: "UNI-SLM-01",
        name: "Classic Cone 100ml Van & Cho",
        description: "Aavin ice cream - Classic Cone Vanilla & Chocolate - GST 5%",
        price: "20.00",
        category: "Ice Cream",
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-ICE-006",
        subcategory: "Ice Cream Cone",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "10.00",
        districtUnionPrice: "11.00",
        wholesalePrice: "13.00",
        retailPrice: "17.00",
        retailerPrice: null,
        mrp: "20.00",
        unitSize: "100",
        unitType: "ml",
        productSegment: "Ice Cream",
        packagingType: "box",
        unitsPerPackage: 20,
        packageWeight: null,
        packageWeightUnit: null,
      },
      {
        id: "slm-ic-007",
        restaurantId: "UNI-SLM-01",
        name: "Classic Cone Van/Cho/BS 50ml",
        description: "Aavin ice cream - Classic Cone Vanilla/Chocolate/Butterscotch - GST 5%",
        price: "10.00",
        category: "Ice Cream",
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-ICE-007",
        subcategory: "Ice Cream Cone",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "5.00",
        districtUnionPrice: "5.50",
        wholesalePrice: "6.50",
        retailPrice: "8.50",
        retailerPrice: null,
        mrp: "10.00",
        unitSize: "50",
        unitType: "ml",
        productSegment: "Ice Cream",
        packagingType: "box",
        unitsPerPackage: 20,
        packageWeight: null,
        packageWeightUnit: null,
      },
      {
        id: "slm-ic-008",
        restaurantId: "UNI-SLM-01",
        name: "Choco Bar 65ml",
        description: "Aavin ice cream - Choco Bar - GST 5%",
        price: "15.00",
        category: "Ice Cream",
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-ICE-008",
        subcategory: "Ice Cream Bar",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "7.50",
        districtUnionPrice: "8.25",
        wholesalePrice: "9.75",
        retailPrice: "12.75",
        retailerPrice: null,
        mrp: "15.00",
        unitSize: "65",
        unitType: "ml",
        productSegment: "Ice Cream",
        packagingType: "box",
        unitsPerPackage: 20,
        packageWeight: null,
        packageWeightUnit: null,
      },
      {
        id: "slm-ic-009",
        restaurantId: "UNI-SLM-01",
        name: "Vanilla 100ml Cup",
        description: "Aavin ice cream - Vanilla - GST 5%",
        price: "15.00",
        category: "Ice Cream",
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-ICE-009",
        subcategory: "Ice Cream Cup",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "7.50",
        districtUnionPrice: "8.25",
        wholesalePrice: "9.75",
        retailPrice: "12.75",
        retailerPrice: null,
        mrp: "15.00",
        unitSize: "100",
        unitType: "ml",
        productSegment: "Ice Cream",
        packagingType: "box",
        unitsPerPackage: 18,
        packageWeight: null,
        packageWeightUnit: null,
      },
      {
        id: "slm-ic-010",
        restaurantId: "UNI-SLM-01",
        name: "Strawberry 100ml Cup",
        description: "Aavin ice cream - Strawberry - GST 5%",
        price: "15.00",
        category: "Ice Cream",
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-ICE-010",
        subcategory: "Ice Cream Cup",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "7.50",
        districtUnionPrice: "8.25",
        wholesalePrice: "9.75",
        retailPrice: "12.75",
        retailerPrice: null,
        mrp: "15.00",
        unitSize: "100",
        unitType: "ml",
        productSegment: "Ice Cream",
        packagingType: "box",
        unitsPerPackage: 18,
        packageWeight: null,
        packageWeightUnit: null,
      },
      {
        id: "slm-ic-011",
        restaurantId: "UNI-SLM-01",
        name: "Mango 100ml Cup",
        description: "Aavin ice cream - Mango - GST 5%",
        price: "15.00",
        category: "Ice Cream",
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-ICE-011",
        subcategory: "Ice Cream Cup",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "7.50",
        districtUnionPrice: "8.25",
        wholesalePrice: "9.75",
        retailPrice: "12.75",
        retailerPrice: null,
        mrp: "15.00",
        unitSize: "100",
        unitType: "ml",
        productSegment: "Ice Cream",
        packagingType: "box",
        unitsPerPackage: 18,
        packageWeight: null,
        packageWeightUnit: null,
      },
      {
        id: "slm-ic-012",
        restaurantId: "UNI-SLM-01",
        name: "Chocolate 100ml Cup",
        description: "Aavin ice cream - Chocolate - GST 5%",
        price: "15.00",
        category: "Ice Cream",
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-ICE-012",
        subcategory: "Ice Cream Cup",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "7.50",
        districtUnionPrice: "8.25",
        wholesalePrice: "9.75",
        retailPrice: "12.75",
        retailerPrice: null,
        mrp: "15.00",
        unitSize: "100",
        unitType: "ml",
        productSegment: "Ice Cream",
        packagingType: "box",
        unitsPerPackage: 18,
        packageWeight: null,
        packageWeightUnit: null,
      },
      {
        id: "slm-ic-013",
        restaurantId: "UNI-SLM-01",
        name: "Pista 100ml Cup",
        description: "Aavin ice cream - Pista - GST 5%",
        price: "15.00",
        category: "Ice Cream",
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-ICE-013",
        subcategory: "Ice Cream Cup",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "7.50",
        districtUnionPrice: "8.25",
        wholesalePrice: "9.75",
        retailPrice: "12.75",
        retailerPrice: null,
        mrp: "15.00",
        unitSize: "100",
        unitType: "ml",
        productSegment: "Ice Cream",
        packagingType: "box",
        unitsPerPackage: 18,
        packageWeight: null,
        packageWeightUnit: null,
      },
      {
        id: "slm-ic-014",
        restaurantId: "UNI-SLM-01",
        name: "Butterscotch 100ml Cup",
        description: "Aavin ice cream - Butterscotch - GST 5%",
        price: "15.00",
        category: "Ice Cream",
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-ICE-014",
        subcategory: "Ice Cream Cup",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "7.50",
        districtUnionPrice: "8.25",
        wholesalePrice: "9.75",
        retailPrice: "12.75",
        retailerPrice: null,
        mrp: "15.00",
        unitSize: "100",
        unitType: "ml",
        productSegment: "Ice Cream",
        packagingType: "box",
        unitsPerPackage: 18,
        packageWeight: null,
        packageWeightUnit: null,
      },
      {
        id: "slm-ic-015",
        restaurantId: "UNI-SLM-01",
        name: "Badam 100ml Cup",
        description: "Aavin ice cream - Badam - GST 5%",
        price: "15.00",
        category: "Ice Cream",
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-ICE-015",
        subcategory: "Ice Cream Cup",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "7.50",
        districtUnionPrice: "8.25",
        wholesalePrice: "9.75",
        retailPrice: "12.75",
        retailerPrice: null,
        mrp: "15.00",
        unitSize: "100",
        unitType: "ml",
        productSegment: "Ice Cream",
        packagingType: "box",
        unitsPerPackage: 18,
        packageWeight: null,
        packageWeightUnit: null,
      },
      {
        id: "slm-ic-016",
        restaurantId: "UNI-SLM-01",
        name: "Vanilla 500ml Tub",
        description: "Aavin ice cream - Vanilla Family Tub - GST 5%",
        price: "50.00",
        category: "Ice Cream",
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-ICE-016",
        subcategory: "Ice Cream Family",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "25.00",
        districtUnionPrice: "27.50",
        wholesalePrice: "32.50",
        retailPrice: "42.50",
        retailerPrice: null,
        mrp: "50.00",
        unitSize: "500",
        unitType: "ml",
        productSegment: "Ice Cream",
        packagingType: "box",
        unitsPerPackage: 1,
        packageWeight: null,
        packageWeightUnit: null,
      },
      {
        id: "slm-ic-017",
        restaurantId: "UNI-SLM-01",
        name: "Mango/S.Berry 500ml Tub",
        description: "Aavin ice cream - Mango/Strawberry Family Tub - GST 5%",
        price: "50.00",
        category: "Ice Cream",
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-ICE-017",
        subcategory: "Ice Cream Family",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "25.00",
        districtUnionPrice: "27.50",
        wholesalePrice: "32.50",
        retailPrice: "42.50",
        retailerPrice: null,
        mrp: "50.00",
        unitSize: "500",
        unitType: "ml",
        productSegment: "Ice Cream",
        packagingType: "box",
        unitsPerPackage: 1,
        packageWeight: null,
        packageWeightUnit: null,
      },
      {
        id: "slm-ic-018",
        restaurantId: "UNI-SLM-01",
        name: "Chocolate 500ml Tub",
        description: "Aavin ice cream - Chocolate Family Tub - GST 5%",
        price: "50.00",
        category: "Ice Cream",
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-ICE-018",
        subcategory: "Ice Cream Family",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "25.00",
        districtUnionPrice: "27.50",
        wholesalePrice: "32.50",
        retailPrice: "42.50",
        retailerPrice: null,
        mrp: "50.00",
        unitSize: "500",
        unitType: "ml",
        productSegment: "Ice Cream",
        packagingType: "box",
        unitsPerPackage: 1,
        packageWeight: null,
        packageWeightUnit: null,
      },
      {
        id: "slm-ic-019",
        restaurantId: "UNI-SLM-01",
        name: "Pis/Badam/B.S 500ml Tub",
        description: "Aavin ice cream - Pista/Badam/Butterscotch Family Tub - GST 5%",
        price: "50.00",
        category: "Ice Cream",
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-ICE-019",
        subcategory: "Ice Cream Family",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "25.00",
        districtUnionPrice: "27.50",
        wholesalePrice: "32.50",
        retailPrice: "42.50",
        retailerPrice: null,
        mrp: "50.00",
        unitSize: "500",
        unitType: "ml",
        productSegment: "Ice Cream",
        packagingType: "box",
        unitsPerPackage: 1,
        packageWeight: null,
        packageWeightUnit: null,
      },
      {
        id: "slm-ic-020",
        restaurantId: "UNI-SLM-01",
        name: "Org/Grape Candy 60ml",
        description: "Aavin ice cream - Orange/Grape Candy - GST 5%",
        price: "10.00",
        category: "Ice Cream",
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-ICE-020",
        subcategory: "Ice Cream Candy",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "5.00",
        districtUnionPrice: "5.50",
        wholesalePrice: "6.50",
        retailPrice: "8.50",
        retailerPrice: null,
        mrp: "10.00",
        unitSize: "60",
        unitType: "ml",
        productSegment: "Ice Cream",
        packagingType: "box",
        unitsPerPackage: 20,
        packageWeight: null,
        packageWeightUnit: null,
      },
      {
        id: "slm-ic-021",
        restaurantId: "UNI-SLM-01",
        name: "Candy Mango 60ml",
        description: "Aavin ice cream - Mango Candy - GST 5%",
        price: "10.00",
        category: "Ice Cream",
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-ICE-021",
        subcategory: "Ice Cream Candy",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "5.00",
        districtUnionPrice: "5.50",
        wholesalePrice: "6.50",
        retailPrice: "8.50",
        retailerPrice: null,
        mrp: "10.00",
        unitSize: "60",
        unitType: "ml",
        productSegment: "Ice Cream",
        packagingType: "box",
        unitsPerPackage: 20,
        packageWeight: null,
        packageWeightUnit: null,
      },
      {
        id: "slm-ic-022",
        restaurantId: "UNI-SLM-01",
        name: "Str Candy 60ml",
        description: "Aavin ice cream - Strawberry Candy - GST 5%",
        price: "10.00",
        category: "Ice Cream",
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-ICE-022",
        subcategory: "Ice Cream Candy",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "5.00",
        districtUnionPrice: "5.50",
        wholesalePrice: "6.50",
        retailPrice: "8.50",
        retailerPrice: null,
        mrp: "10.00",
        unitSize: "60",
        unitType: "ml",
        productSegment: "Ice Cream",
        packagingType: "box",
        unitsPerPackage: 20,
        packageWeight: null,
        packageWeightUnit: null,
      },
      {
        id: "slm-ic-023",
        restaurantId: "UNI-SLM-01",
        name: "Grape/Mango Duet 60ml",
        description: "Aavin ice cream - Grape/Mango Duet - GST 5%",
        price: "10.00",
        category: "Ice Cream",
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-ICE-023",
        subcategory: "Ice Cream Candy",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "5.00",
        districtUnionPrice: "5.50",
        wholesalePrice: "6.50",
        retailPrice: "8.50",
        retailerPrice: null,
        mrp: "10.00",
        unitSize: "60",
        unitType: "ml",
        productSegment: "Ice Cream",
        packagingType: "box",
        unitsPerPackage: 20,
        packageWeight: null,
        packageWeightUnit: null,
      },
      {
        id: "slm-ic-024",
        restaurantId: "UNI-SLM-01",
        name: "Ball Ice Cream 125ml",
        description: "Aavin ice cream - Ball Ice Cream - GST 5%",
        price: "20.00",
        category: "Ice Cream",
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-ICE-024",
        subcategory: "Ice Cream Ball",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "10.00",
        districtUnionPrice: "11.00",
        wholesalePrice: "13.00",
        retailPrice: "17.00",
        retailerPrice: null,
        mrp: "20.00",
        unitSize: "125",
        unitType: "ml",
        productSegment: "Ice Cream",
        packagingType: "box",
        unitsPerPackage: 1,
        packageWeight: null,
        packageWeightUnit: null,
      },
      {
        id: "slm-ic-025",
        restaurantId: "UNI-SLM-01",
        name: "Mini Kulfi 25ml",
        description: "Aavin ice cream - Mini Kulfi - GST 5%",
        price: "5.00",
        category: "Ice Cream",
        image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        isAvailable: true,
        createdAt: new Date(),
        productCode: "SLM-ICE-025",
        subcategory: "Ice Cream Kulfi",
        hsnCode: null,
        gstPercent: "5.00",
        federationPrice: "2.50",
        districtUnionPrice: "2.75",
        wholesalePrice: "3.25",
        retailPrice: "4.25",
        retailerPrice: null,
        mrp: "5.00",
        unitSize: "25",
        unitType: "ml",
        productSegment: "Ice Cream",
        packagingType: "box",
        unitsPerPackage: 50,
        packageWeight: null,
        packageWeightUnit: null,
      },
    ];

    sampleMenuItems.forEach(item => {
      this.menuItems.set(item.id, item);
    });
  }

  protected async seedAdminUserSync() {
    const salt = '550e8400e29b41d4a716446655440000';
    const password = 'Aavincart@123';
    const hash = scryptSync(password, salt, 64);

    try {
      await db.insert(users).values({
        id: 'admin-1',
        name: 'Administrator',
        email: 'aavincart@gmail.com',
        passwordHash: `${salt}:${hash.toString('hex')}`,
        role: 'admin',
        status: 'approved',
        restaurantId: null,
      }).onConflictDoNothing({ target: users.email });
    } catch (e) { /* ignore duplicate */ }

    const merchantPassword = '9843777277';
    const merchantHash = scryptSync(merchantPassword, salt, 64);
    try {
      await db.insert(users).values({
        id: 'salem-merchant-1',
        name: 'Salem Union Manager',
        email: 'salem@aavin.com',
        passwordHash: `${salt}:${merchantHash.toString('hex')}`,
        role: 'merchant',
        status: 'approved',
        restaurantId: 'merchant-3',
      }).onConflictDoNothing({ target: users.email });
    } catch (e) { /* ignore duplicate */ }

    const driverPassword = '9843777277';
    const driverHash = scryptSync(driverPassword, salt, 64);
    try {
      await db.insert(users).values({
        id: 'driver-demo-1',
        name: 'Demo Delivery Driver',
        email: 'driver@demo.com',
        passwordHash: `${salt}:${driverHash.toString('hex')}`,
        role: 'driver',
        status: 'approved',
        restaurantId: 'merchant-3',
      }).onConflictDoNothing({ target: users.email });
    } catch (e) { /* ignore duplicate */ }

    await this.seedSalemB2BUsers(salt);
  }

  private async seedSalemB2BUsers(salt: string) {
    try {
      const existingCount = await db.select({ count: sql<number>`count(*)` }).from(users).where(sql`id LIKE 'salem-b2b-%'`);
      const count = Number(existingCount[0]?.count || 0);
      if (count > 100) {
        return;
      }

      const jsonPath = `${process.cwd()}/attached_assets/Aavincart-B2B_USERS.json`;
      const data = JSON.parse(readFileSync(jsonPath, 'utf-8'));

      const defaultPassword = 'Aavincart@123';
      const pwHash = scryptSync(defaultPassword, salt, 64);
      const passwordHash = `${salt}:${pwHash.toString('hex')}`;

      const customPasswords: Record<string, string> = {
        'WSD016': 'Wsd@16',
        'WSD025': 'Nagaas@1978',
      };

      const businessTypePrefixMap: Record<string, string> = {
        'WSD': 'AA',
        'DLR': 'AA',
        'MPCS': 'MP',
        'HOTELS': 'HT',
        'HOTEL': 'HT',
        'INSTUTION': 'IN',
        'INSTITUTION': 'IN',
        'PRIVATE PARLOUR': 'PP',
        'UNION PARLOUR': 'UP',
        'Union Parlour': 'UP',
        'GENERAL SHOP': 'GS',
        'RETAIL': 'GS',
      };

      const tierCodeToRole: Record<string, string> = {
        'DLR': 'DEALER',
        'WSD': 'WHOLESALE_DEALER',
        'RTL': 'RETAILER',
        'RTR': 'RETAILER',
        'MRP': 'MRP',
        'FED': 'FEDERATION',
        'INT': 'INTER_UNION',
      };

      const businessTypeToRole: Record<string, string> = {
        'WSD': 'wholesale_dealer',
        'DLR': 'dealer',
        'MPCS': 'dealer',
        'HOTELS': 'dealer',
        'HOTEL': 'dealer',
        'INSTUTION': 'dealer',
        'INSTITUTION': 'dealer',
        'PRIVATE PARLOUR': 'dealer',
        'UNION PARLOUR': 'dealer',
        'Union Parlour': 'dealer',
        'GENERAL SHOP': 'dealer',
        'RETAIL': 'dealer',
      };

      const counters: Record<string, number> = {};
      let imported = 0;

      for (const row of data as any[]) {
        if (!row['Business Name'] || !row['Business Type']) continue;

        const businessType = String(row['Business Type']).trim();
        const prefix = businessTypePrefixMap[businessType] || 'AA';
        let businessCode = row['Business Code'] ? String(row['Business Code']).trim() : '';

        if (!businessCode || /^\d+$/.test(businessCode)) {
          const numPart = businessCode || '';
          const padded = numPart.padStart(4, '0');
          businessCode = `${prefix}${padded}`;
        }

        if (!businessCode) {
          const key = prefix;
          counters[key] = (counters[key] || 0) + 1;
          businessCode = `${prefix}${String(counters[key]).padStart(4, '0')}`;
        }

        const phone = row['Phone'] ? String(row['Phone']).trim() : '';
        const email = `${businessCode.toLowerCase()}@aavincart.com`;
        const role = businessTypeToRole[businessType] || 'dealer';

        const fmTier = row['Fresh Milk -Pricing Tier'] ? String(row['Fresh Milk -Pricing Tier']).trim().toUpperCase() : '';
        const pTier = row['Products-Pricing Tier'] ? String(row['Products-Pricing Tier']).trim().toUpperCase() : '';
        const icTier = row['Ice Creams-Pricing Tier'] ? String(row['Ice Creams-Pricing Tier']).trim().toUpperCase() : '';

        const userId = `salem-b2b-${businessCode.toLowerCase()}`;

        let userPasswordHash = passwordHash;
        if (customPasswords[businessCode]) {
          const customPwHash = scryptSync(customPasswords[businessCode], salt, 64);
          userPasswordHash = `${salt}:${customPwHash.toString('hex')}`;
        }

        const userPlainPassword = customPasswords[businessCode] || defaultPassword;

        const user: any = {
          id: userId,
          name: businessCode,
          phone: phone,
          email: email,
          passwordHash: userPasswordHash,
          plainPassword: userPlainPassword,
          role: role,
          pricingRole: tierCodeToRole[fmTier] || tierCodeToRole[pTier] || 'DEALER',
          freshMilkPricingRole: tierCodeToRole[fmTier] || 'MRP',
          productsPricingRole: tierCodeToRole[pTier] || 'MRP',
          iceCreamPricingRole: tierCodeToRole[icTier] || 'MRP',
          unionId: 'merchant-3',
          restaurantId: null,
          district: row['District'] ? String(row['District']).trim() : 'Salem',
          districtUnion: 'Salem District Cooperative Milk Producers Union Ltd',
          office: row['Office'] ? String(row['Office']).trim() : '',
          businessType: businessType,
          businessTypeCode: prefix,
          businessRoute: row['Business Route'] ? String(row['Business Route']).trim() : '',
          businessPoint: row['Business Point'] ? String(row['Business Point']).trim() : '',
          businessCode: businessCode,
          businessName: String(row['Business Name']).trim(),
          businessAddress: row['Business Address'] ? String(row['Business Address']).trim() : '',
          gstNumber: row['GSTIN'] ? String(row['GSTIN']).trim() : null,
          status: 'active',
          createdAt: new Date(),
          updatedAt: new Date(),
        };

        try {
          await db.insert(users).values({
            ...user,
            status: 'approved',
          }).onConflictDoNothing({ target: users.email });
        } catch (e) { /* ignore duplicate */ }
        imported++;
      }

    } catch (error) {
      console.error('Failed to seed Salem B2B users from Excel:', error);
    }
  }

  protected seedKarenderiaData() {
    // Seed AAVIN District Union merchants - all 27 unions with detailed profiles
    const aavinUnions = aavinUnionsData;

    const sampleMerchants: Merchant[] = aavinUnions.map((union, index) => ({
      id: `merchant-${union.id}`,
      merchantUuid: `uuid-merchant-${union.id}`,
      restaurantSlug: union.slug,
      restaurantName: union.fullName,
      restaurantPhone: union.phone,
      contactName: `District Manager - ${union.name}`,
      contactPhone: union.phone,
      contactEmail: union.email,
      address: union.address,
      freeDelivery: 1,
      username: union.username,
      password: "password123",
      status: index < 15 ? "active" : "pending",
      dateActivated: index < 15 ? new Date() : null,
      isFeatured: index < 5 ? 1 : 0,
      isReady: 1,
      isSponsored: index < 3 ? 1 : 0,
      isCommission: 1,
      percentCommission: "10.00",
      commissionBased: "gross",
      latitude: union.lat,
      longitude: union.lng,
      logo: "",
      path: "/uploads/merchants/",
      merchantType: 1,
      membershipExpired: null,
      commissionType: "percentage",
      packageId: 1,
      deliveryDistanceCovered: "15.00",
      headerImage: "",
      description: `${union.fullName} - Products: ${union.products}. Milk Procurement: ${union.milkProcurement}. Cooperative Societies: ${union.societies}. Registered Farmers: ${union.farmers.toLocaleString()}`,
      shortDescription: `AAVIN ${union.name} - ${union.products.split(',').slice(0, 4).join(', ')}`,
      closeStore: 0,
      disabledOrdering: 0,
      pauseOrdering: 0,
      ordersAdded: Math.floor(Math.random() * 500),
      orderLimit: 1000,
      itemsAdded: 25,
      itemLimit: 100,
      lastLogin: index < 15 ? new Date() : null,
      selfDelivery: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    }));

    sampleMerchants.forEach(merchant => {
      this.merchants.set(merchant.id, merchant);
    });

    // Seed plans for AAVIN dairy unions
    const samplePlans: Plan[] = [
      {
        id: "plan-1",
        planName: "District Union Basic",
        planDescription: "For small district cooperative milk producers unions",
        planPrice: "999.00",
        planDuration: 30,
        maxItems: 50,
        maxOrders: 500,
        commissionRate: "10.00",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "plan-2",
        planName: "District Union Standard",
        planDescription: "For medium-sized district unions with higher volume",
        planPrice: "1999.00",
        planDuration: 30,
        maxItems: 150,
        maxOrders: 2000,
        commissionRate: "8.00",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "plan-3",
        planName: "District Union Premium",
        planDescription: "Unlimited features for major district unions like Chennai, Coimbatore",
        planPrice: "4999.00",
        planDuration: 30,
        maxItems: 0, // unlimited
        maxOrders: 0, // unlimited
        commissionRate: "5.00",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ];

    samplePlans.forEach(plan => {
      this.plans.set(plan.id, plan);
    });

    // Seed clients
    const sampleClients: Client[] = [
      {
        id: "client-1",
        clientUuid: "uuid-client-1",
        socialStrategy: "web",
        merchantId: 0,
        firstName: "John",
        lastName: "Doe",
        emailAddress: "john.doe@example.com",
        password: "password123",
        phonePrefix: "+1",
        contactPhone: "5551234567",
        avatar: "avatar1.jpg",
        path: "/uploads/clients/",
        status: "active",
        socialId: "",
        socialToken: null,
        token: "token123",
        mobileVerificationCode: 0,
        accountVerified: 1,
        verifyCodeRequested: new Date(),
        resetPasswordRequest: 0,
        lastLogin: new Date(),
        dateCreated: new Date(),
        dateModified: new Date(),
        ipAddress: "192.168.1.1",
      },
      {
        id: "client-2",
        clientUuid: "uuid-client-2",
        socialStrategy: "web",
        merchantId: 0,
        firstName: "Jane",
        lastName: "Smith",
        emailAddress: "jane.smith@example.com",
        password: "password123",
        phonePrefix: "+1",
        contactPhone: "5551234568",
        avatar: "avatar2.jpg",
        path: "/uploads/clients/",
        status: "active",
        socialId: "",
        socialToken: null,
        token: "token456",
        mobileVerificationCode: 0,
        accountVerified: 1,
        verifyCodeRequested: new Date(),
        resetPasswordRequest: 0,
        lastLogin: new Date(),
        dateCreated: new Date(),
        dateModified: new Date(),
        ipAddress: "192.168.1.2",
      },
    ];

    sampleClients.forEach(client => {
      this.clients.set(client.id, client);
    });

    // Seed payment gateways
    const samplePaymentGateways: PaymentGateway[] = [
      {
        id: "gateway-2",
        paymentCode: "paypal",
        paymentName: "PayPal",
        onlinePayment: true,
        availableForPayout: true,
        availableForPlan: true,
        logoType: "image",
        logoImage: "",
        logoClassIcon: "fa-paypal",
        featuredImage: "",
        isProduction: false,
        secretKey: "",
        publishableKey: "",
        webhooksSigningSecret: "",
        webhooksPlan: "",
        events: "payment.completed, payment.failed, subscription.created, subscription.cancelled",
        status: "inactive",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "gateway-3",
        paymentCode: "razorpay",
        paymentName: "Razorpay",
        onlinePayment: true,
        availableForPayout: false,
        availableForPlan: true,
        logoType: "image",
        logoImage: "",
        logoClassIcon: "fa-credit-card-alt",
        featuredImage: "",
        isProduction: true,
        secretKey: process.env.RAZORPAY_KEY_SECRET || "",
        publishableKey: process.env.RAZORPAY_KEY_ID || "",
        webhooksSigningSecret: "",
        webhooksPlan: "",
        events: "payment.captured, payment.failed, subscription.charged, subscription.cancelled",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "gateway-4",
        paymentCode: "sbi_upi",
        paymentName: "SBI UPI",
        onlinePayment: true,
        availableForPayout: false,
        availableForPlan: true,
        logoType: "image",
        logoImage: "",
        logoClassIcon: "fa-university",
        featuredImage: "",
        isProduction: false,
        secretKey: "sbi_upi_test_secret_key", // SBI UPI Client Secret Key
        publishableKey: "merchantvpa@sbi", // SBI UPI Merchant VPA (Virtual Payment Address)
        webhooksSigningSecret: "sbi_upi_webhook_secret_key", // SBI UPI Webhook Secret
        webhooksPlan: "https://nagaraatreif.com/sbi-upi/api/v1/webhooks",
        events: "payment.success, payment.failed, payment.expired, payment.pending",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "cashfree-gateway",
        paymentCode: "cashfree",
        paymentName: "Cashfree",
        onlinePayment: true,
        availableForPayout: true,
        availableForPlan: true,
        logoType: "icon",
        logoImage: "",
        logoClassIcon: "fa-credit-card",
        featuredImage: "",
        isProduction: false,
        secretKey: "",
        publishableKey: "",
        webhooksSigningSecret: "",
        webhooksPlan: "",
        events: "PAYMENT_SUCCESS_WEBHOOK, PAYMENT_FAILED_WEBHOOK, REFUND_STATUS",
        status: "active",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ];

    samplePaymentGateways.forEach(gateway => {
      this.paymentGateways.set(gateway.id, gateway);
    });

    // Seed default categories for all merchants
    const defaultCategories = [
      { name: 'Milk', sortOrder: 1 },
      { name: 'Curd', sortOrder: 2 },
      { name: 'Paneer', sortOrder: 3 },
      { name: 'Butter', sortOrder: 4 },
      { name: 'Ghee', sortOrder: 5 },
      { name: 'Buttermilk', sortOrder: 6 },
      { name: 'Ice Cream', sortOrder: 7 },
      { name: 'Sweets', sortOrder: 8 },
      { name: 'Flavoured Milk', sortOrder: 9 },
      { name: 'Milk Powder', sortOrder: 10 },
    ];

    // Add categories for merchant-3 (Salem Union) and other merchants
    ['merchant-1', 'merchant-2', 'merchant-3', 'merchant-4', 'merchant-5'].forEach(merchantId => {
      defaultCategories.forEach(cat => {
        const id = `cat-${merchantId}-${cat.sortOrder}`;
        this.categories.set(id, {
          id,
          merchantId,
          name: cat.name,
          isActive: true,
          sortOrder: cat.sortOrder,
        });
      });
    });

    const salemRoutes = [
      "ATTUR", "HASTHAMPATTY", "FREE MILK - STAFF", "H.O.PARLOUR/DAY", "KOTTAI DAY",
      "STEELPLANT DAY", "ALAGAPURAM DAY", "SHEVAPET DAY", "PATTAKOIL DAY", "PONNAMMAPET DAY",
      "DHATHAGAPATTY DAY", "ELAMPILLAI", "OMALUR DAY", "AYOTHIYAPATINAM", "HORECA 5 ROAD",
      "SANKAGIRI EDPY", "PANAMARATHUPATTI", "EDAPADY DAY (MTR)", "METTUR MINI DAY",
      "KONDAPANAYAKANPATTI", "GUGAI DAY"
    ];
    const namakkalRoutes = [
      "T.GODE 1", "NAMAKKAL DAY", "RASIPURAM DAY", "PALLIPALYAM DAY",
      "KUMARAPALAYAM DAY", "P.VELLUR DAY"
    ];

    salemRoutes.forEach((name, idx) => {
      const id = `fmr-slm-${idx + 1}`;
      this.freshMilkRoutesMap.set(id, {
        id, unionId: "UNI-SLM-01", routeName: name,
        areaGroup: "Salem", sequenceNo: idx + 1, isActive: true, createdAt: new Date(),
      });
    });
    namakkalRoutes.forEach((name, idx) => {
      const id = `fmr-nmk-${idx + 1}`;
      this.freshMilkRoutesMap.set(id, {
        id, unionId: "UNI-SLM-01", routeName: name,
        areaGroup: "Namakkal", sequenceNo: idx + 1, isActive: true, createdAt: new Date(),
      });
    });

  }


}
